/*
 * ListenBrainz Swagger - OpenAPI 3.0
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hihn.listenbrainz;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.hihn.listenbrainz.ArtistMetadataTag;
import org.hihn.listenbrainz.Rels1;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ArtistMetadata
 */
public class ArtistMetadataTest {
    private final ArtistMetadata model = new ArtistMetadata();

    /**
     * Model tests for ArtistMetadata
     */
    @Test
    public void testArtistMetadata() {
        // TODO: test ArtistMetadata
    }

    /**
     * Test the property 'area'
     */
    @Test
    public void areaTest() {
        // TODO: test area
    }

    /**
     * Test the property 'artistMbid'
     */
    @Test
    public void artistMbidTest() {
        // TODO: test artistMbid
    }

    /**
     * Test the property 'beginYear'
     */
    @Test
    public void beginYearTest() {
        // TODO: test beginYear
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'mbid'
     */
    @Test
    public void mbidTest() {
        // TODO: test mbid
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'rels'
     */
    @Test
    public void relsTest() {
        // TODO: test rels
    }

    /**
     * Test the property 'tag'
     */
    @Test
    public void tagTest() {
        // TODO: test tag
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
