/*
 * ListenBrainz Swagger - OpenAPI 3.0
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hihn.listenbrainz;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.hihn.listenbrainz.Metadata;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FeedEventsListensSimilarPayloadEventsInner
 */
public class FeedEventsListensSimilarPayloadEventsInnerTest {
    private final FeedEventsListensSimilarPayloadEventsInner model = new FeedEventsListensSimilarPayloadEventsInner();

    /**
     * Model tests for FeedEventsListensSimilarPayloadEventsInner
     */
    @Test
    public void testFeedEventsListensSimilarPayloadEventsInner() {
        // TODO: test FeedEventsListensSimilarPayloadEventsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'hidden'
     */
    @Test
    public void hiddenTest() {
        // TODO: test hidden
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'similarity'
     */
    @Test
    public void similarityTest() {
        // TODO: test similarity
    }

    /**
     * Test the property 'userName'
     */
    @Test
    public void userNameTest() {
        // TODO: test userName
    }

}
