/*
 * ListenBrainz Swagger - OpenAPI 3.0
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hihn.listenbrainz;

import org.hihn.listenbrainz.ApiException;
import org.hihn.listenbrainz.AllowedStatisticsRange;
import org.hihn.listenbrainz.CoverTypes;
import org.hihn.listenbrainz.CreateCoverArtGrid;
import java.io.File;
import org.hihn.listenbrainz.YearInMusicImage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LbArtApi
 */
@Disabled
public class LbArtApiTest {

    private final LbArtApi api = new LbArtApi();

    /**
     * Create a cover art grid SVG file from the POSTed JSON data to this endpoint.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createCoverArtGridTest() throws ApiException {
        CreateCoverArtGrid createCoverArtGrid = null;
        File response = api.createCoverArtGrid(createCoverArtGrid)
                .execute();
        // TODO: test validations
    }

    /**
     * Create a cover art grid SVG file from the stats of a given user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createCoverArtGridForUserTest() throws ApiException {
        String userName = null;
        AllowedStatisticsRange timeRange = null;
        Integer dimension = null;
        Integer layout = null;
        Integer imageSize = null;
        File response = api.createCoverArtGridForUser(userName, timeRange, dimension, layout, imageSize)
                .execute();
        // TODO: test validations
    }

    /**
     * Create a custom cover art SVG file from the stats of a given user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createCustomCoverArtTest() throws ApiException {
        CoverTypes customName = null;
        String userName = null;
        AllowedStatisticsRange timeRange = null;
        Integer imageSize = null;
        File response = api.createCustomCoverArt(customName, userName, timeRange, imageSize)
                .execute();
        // TODO: test validations
    }

    /**
     * Create the shareable svg image using YIM stats.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void yearInMusicTest() throws ApiException {
        Integer year = null;
        String userName = null;
        YearInMusicImage image = null;
        File response = api.yearInMusic(year, userName, image)
                .execute();
        // TODO: test validations
    }

}
