/*
 * ListenBrainz Swagger - OpenAPI 3.0
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hihn.listenbrainz;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.hihn.listenbrainz.ListenersForArtistPayloadListenersInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListenersForReleaseGroupPayload
 */
public class ListenersForReleaseGroupPayloadTest {
    private final ListenersForReleaseGroupPayload model = new ListenersForReleaseGroupPayload();

    /**
     * Model tests for ListenersForReleaseGroupPayload
     */
    @Test
    public void testListenersForReleaseGroupPayload() {
        // TODO: test ListenersForReleaseGroupPayload
    }

    /**
     * Test the property 'artistMbids'
     */
    @Test
    public void artistMbidsTest() {
        // TODO: test artistMbids
    }

    /**
     * Test the property 'artistName'
     */
    @Test
    public void artistNameTest() {
        // TODO: test artistName
    }

    /**
     * Test the property 'caaId'
     */
    @Test
    public void caaIdTest() {
        // TODO: test caaId
    }

    /**
     * Test the property 'caaReleaseMbid'
     */
    @Test
    public void caaReleaseMbidTest() {
        // TODO: test caaReleaseMbid
    }

    /**
     * Test the property 'fromTs'
     */
    @Test
    public void fromTsTest() {
        // TODO: test fromTs
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

    /**
     * Test the property 'listeners'
     */
    @Test
    public void listenersTest() {
        // TODO: test listeners
    }

    /**
     * Test the property 'releaseGroupMbid'
     */
    @Test
    public void releaseGroupMbidTest() {
        // TODO: test releaseGroupMbid
    }

    /**
     * Test the property 'releaseGroupName'
     */
    @Test
    public void releaseGroupNameTest() {
        // TODO: test releaseGroupName
    }

    /**
     * Test the property 'statsRange'
     */
    @Test
    public void statsRangeTest() {
        // TODO: test statsRange
    }

    /**
     * Test the property 'toTs'
     */
    @Test
    public void toTsTest() {
        // TODO: test toTs
    }

    /**
     * Test the property 'totalListenCount'
     */
    @Test
    public void totalListenCountTest() {
        // TODO: test totalListenCount
    }

    /**
     * Test the property 'totalUserCount'
     */
    @Test
    public void totalUserCountTest() {
        // TODO: test totalUserCount
    }

}
