/*
 * ListenBrainz Swagger - OpenAPI 3.0
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hihn.listenbrainz;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.hihn.listenbrainz.ListeningActivityForUserPayloadListeningActivityInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListeningActivityForUserPayload
 */
public class ListeningActivityForUserPayloadTest {
    private final ListeningActivityForUserPayload model = new ListeningActivityForUserPayload();

    /**
     * Model tests for ListeningActivityForUserPayload
     */
    @Test
    public void testListeningActivityForUserPayload() {
        // TODO: test ListeningActivityForUserPayload
    }

    /**
     * Test the property 'fromTs'
     */
    @Test
    public void fromTsTest() {
        // TODO: test fromTs
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

    /**
     * Test the property 'listeningActivity'
     */
    @Test
    public void listeningActivityTest() {
        // TODO: test listeningActivity
    }

    /**
     * Test the property 'range'
     */
    @Test
    public void rangeTest() {
        // TODO: test range
    }

    /**
     * Test the property 'toTs'
     */
    @Test
    public void toTsTest() {
        // TODO: test toTs
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

}
