/*
 * ListenBrainz Swagger - OpenAPI 3.0
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hihn.listenbrainz;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.hihn.listenbrainz.LookupMetadata;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Lookup
 */
public class LookupTest {
    private final Lookup model = new Lookup();

    /**
     * Model tests for Lookup
     */
    @Test
    public void testLookup() {
        // TODO: test Lookup
    }

    /**
     * Test the property 'artistCreditName'
     */
    @Test
    public void artistCreditNameTest() {
        // TODO: test artistCreditName
    }

    /**
     * Test the property 'artistMbids'
     */
    @Test
    public void artistMbidsTest() {
        // TODO: test artistMbids
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'recordingMbid'
     */
    @Test
    public void recordingMbidTest() {
        // TODO: test recordingMbid
    }

    /**
     * Test the property 'recordingName'
     */
    @Test
    public void recordingNameTest() {
        // TODO: test recordingName
    }

    /**
     * Test the property 'releaseMbid'
     */
    @Test
    public void releaseMbidTest() {
        // TODO: test releaseMbid
    }

    /**
     * Test the property 'releaseName'
     */
    @Test
    public void releaseNameTest() {
        // TODO: test releaseName
    }

}
