/*
 * ListenBrainz Swagger - OpenAPI 3.0
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hihn.listenbrainz;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Rels
 */
public class RelsTest {
    private final Rels model = new Rels();

    /**
     * Model tests for Rels
     */
    @Test
    public void testRels() {
        // TODO: test Rels
    }

    /**
     * Test the property 'artistMbid'
     */
    @Test
    public void artistMbidTest() {
        // TODO: test artistMbid
    }

    /**
     * Test the property 'artistName'
     */
    @Test
    public void artistNameTest() {
        // TODO: test artistName
    }

    /**
     * Test the property 'instrument'
     */
    @Test
    public void instrumentTest() {
        // TODO: test instrument
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
