/*
 * ListenBrainz Swagger - OpenAPI 3.0
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hihn.listenbrainz;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.hihn.listenbrainz.TopRecordingsForArtistInnerReleaseColor;
import org.hihn.listenbrainz.TopReleaseGroupsForArtistInnerArtist;
import org.hihn.listenbrainz.TopReleaseGroupsForArtistInnerRelease;
import org.hihn.listenbrainz.TopReleaseGroupsForArtistInnerReleaseGroup;
import org.hihn.listenbrainz.TopReleaseGroupsForArtistInnerTag;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TopReleaseGroupsForArtistInner
 */
public class TopReleaseGroupsForArtistInnerTest {
    private final TopReleaseGroupsForArtistInner model = new TopReleaseGroupsForArtistInner();

    /**
     * Model tests for TopReleaseGroupsForArtistInner
     */
    @Test
    public void testTopReleaseGroupsForArtistInner() {
        // TODO: test TopReleaseGroupsForArtistInner
    }

    /**
     * Test the property 'artist'
     */
    @Test
    public void artistTest() {
        // TODO: test artist
    }

    /**
     * Test the property 'release'
     */
    @Test
    public void releaseTest() {
        // TODO: test release
    }

    /**
     * Test the property 'releaseColor'
     */
    @Test
    public void releaseColorTest() {
        // TODO: test releaseColor
    }

    /**
     * Test the property 'releaseGroup'
     */
    @Test
    public void releaseGroupTest() {
        // TODO: test releaseGroup
    }

    /**
     * Test the property 'releaseGroupMbid'
     */
    @Test
    public void releaseGroupMbidTest() {
        // TODO: test releaseGroupMbid
    }

    /**
     * Test the property 'tag'
     */
    @Test
    public void tagTest() {
        // TODO: test tag
    }

    /**
     * Test the property 'totalListenCount'
     */
    @Test
    public void totalListenCountTest() {
        // TODO: test totalListenCount
    }

    /**
     * Test the property 'totalUserCount'
     */
    @Test
    public void totalUserCountTest() {
        // TODO: test totalUserCount
    }

}
