/*
 * ListenBrainz Swagger - OpenAPI 3.0
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hihn.listenbrainz;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.hihn.listenbrainz.TopReleasesForUserPayloadReleasesInnerArtistsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for YearInMusicForUserPayloadDataNewReleasesOfTopArtistsInner
 */
public class YearInMusicForUserPayloadDataNewReleasesOfTopArtistsInnerTest {
    private final YearInMusicForUserPayloadDataNewReleasesOfTopArtistsInner model = new YearInMusicForUserPayloadDataNewReleasesOfTopArtistsInner();

    /**
     * Model tests for YearInMusicForUserPayloadDataNewReleasesOfTopArtistsInner
     */
    @Test
    public void testYearInMusicForUserPayloadDataNewReleasesOfTopArtistsInner() {
        // TODO: test YearInMusicForUserPayloadDataNewReleasesOfTopArtistsInner
    }

    /**
     * Test the property 'artistCreditMbids'
     */
    @Test
    public void artistCreditMbidsTest() {
        // TODO: test artistCreditMbids
    }

    /**
     * Test the property 'artistCreditName'
     */
    @Test
    public void artistCreditNameTest() {
        // TODO: test artistCreditName
    }

    /**
     * Test the property 'artists'
     */
    @Test
    public void artistsTest() {
        // TODO: test artists
    }

    /**
     * Test the property 'caaId'
     */
    @Test
    public void caaIdTest() {
        // TODO: test caaId
    }

    /**
     * Test the property 'caaReleaseMbid'
     */
    @Test
    public void caaReleaseMbidTest() {
        // TODO: test caaReleaseMbid
    }

    /**
     * Test the property 'releaseGroupMbid'
     */
    @Test
    public void releaseGroupMbidTest() {
        // TODO: test releaseGroupMbid
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
