/*
 * ListenBrainz Swagger - OpenAPI 3.0
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hihn.listenbrainz;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AllowedRatings
 */
@JsonAdapter(AllowedRatings.Adapter.class)
public enum AllowedRatings {
  
  LIKE("like"),
  
  LOVE("love"),
  
  DISLIKE("dislike"),
  
  HATE("hate"),
  
  BAD_RECOMMENDATION("bad_recommendation");

  private String value;

  AllowedRatings(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AllowedRatings fromValue(String value) {
    for (AllowedRatings b : AllowedRatings.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AllowedRatings> {
    @Override
    public void write(final JsonWriter jsonWriter, final AllowedRatings enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AllowedRatings read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AllowedRatings.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    AllowedRatings.fromValue(value);
  }
}

