/*
 * ListenBrainz Swagger - OpenAPI 3.0
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hihn.listenbrainz;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.hihn.listenbrainz.ColorPayloadReleasesInnerRecordingsInnerTrackMetadata;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.hihn.listenbrainz.JSON;

/**
 * ColorPayloadReleasesInnerRecordingsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:00:27.345003+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class ColorPayloadReleasesInnerRecordingsInner {
  public static final String SERIALIZED_NAME_TRACK_METADATA = "track_metadata";
  @SerializedName(SERIALIZED_NAME_TRACK_METADATA)
  private ColorPayloadReleasesInnerRecordingsInnerTrackMetadata trackMetadata;

  public ColorPayloadReleasesInnerRecordingsInner() {
  }

  public ColorPayloadReleasesInnerRecordingsInner trackMetadata(ColorPayloadReleasesInnerRecordingsInnerTrackMetadata trackMetadata) {
    this.trackMetadata = trackMetadata;
    return this;
  }

  /**
   * Get trackMetadata
   * @return trackMetadata
   */
  @javax.annotation.Nullable
  public ColorPayloadReleasesInnerRecordingsInnerTrackMetadata getTrackMetadata() {
    return trackMetadata;
  }

  public void setTrackMetadata(ColorPayloadReleasesInnerRecordingsInnerTrackMetadata trackMetadata) {
    this.trackMetadata = trackMetadata;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ColorPayloadReleasesInnerRecordingsInner colorPayloadReleasesInnerRecordingsInner = (ColorPayloadReleasesInnerRecordingsInner) o;
    return Objects.equals(this.trackMetadata, colorPayloadReleasesInnerRecordingsInner.trackMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trackMetadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ColorPayloadReleasesInnerRecordingsInner {\n");
    sb.append("    trackMetadata: ").append(toIndentedString(trackMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("track_metadata");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ColorPayloadReleasesInnerRecordingsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ColorPayloadReleasesInnerRecordingsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ColorPayloadReleasesInnerRecordingsInner is not found in the empty JSON string", ColorPayloadReleasesInnerRecordingsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ColorPayloadReleasesInnerRecordingsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ColorPayloadReleasesInnerRecordingsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `track_metadata`
      if (jsonObj.get("track_metadata") != null && !jsonObj.get("track_metadata").isJsonNull()) {
        ColorPayloadReleasesInnerRecordingsInnerTrackMetadata.validateJsonElement(jsonObj.get("track_metadata"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ColorPayloadReleasesInnerRecordingsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ColorPayloadReleasesInnerRecordingsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ColorPayloadReleasesInnerRecordingsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ColorPayloadReleasesInnerRecordingsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ColorPayloadReleasesInnerRecordingsInner>() {
           @Override
           public void write(JsonWriter out, ColorPayloadReleasesInnerRecordingsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ColorPayloadReleasesInnerRecordingsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ColorPayloadReleasesInnerRecordingsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ColorPayloadReleasesInnerRecordingsInner
   * @throws IOException if the JSON string is invalid with respect to ColorPayloadReleasesInnerRecordingsInner
   */
  public static ColorPayloadReleasesInnerRecordingsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ColorPayloadReleasesInnerRecordingsInner.class);
  }

  /**
   * Convert an instance of ColorPayloadReleasesInnerRecordingsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

