/*
 * ListenBrainz Swagger - OpenAPI 3.0
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.hihn.listenbrainz;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.hihn.listenbrainz.PlayingNowForUserPayloadListensInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.hihn.listenbrainz.JSON;

/**
 * PlayingNowForUserPayload
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:54:13.371331+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class PlayingNowForUserPayload {
  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Integer count;

  public static final String SERIALIZED_NAME_LISTENS = "listens";
  @SerializedName(SERIALIZED_NAME_LISTENS)
  private List<PlayingNowForUserPayloadListensInner> listens = new ArrayList<>();

  public static final String SERIALIZED_NAME_PLAYING_NOW = "playing_now";
  @SerializedName(SERIALIZED_NAME_PLAYING_NOW)
  private Boolean playingNow;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public PlayingNowForUserPayload() {
  }

  public PlayingNowForUserPayload count(Integer count) {
    this.count = count;
    return this;
  }

  /**
   * Get count
   * @return count
   */
  @javax.annotation.Nonnull
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  public PlayingNowForUserPayload listens(List<PlayingNowForUserPayloadListensInner> listens) {
    this.listens = listens;
    return this;
  }

  public PlayingNowForUserPayload addListensItem(PlayingNowForUserPayloadListensInner listensItem) {
    if (this.listens == null) {
      this.listens = new ArrayList<>();
    }
    this.listens.add(listensItem);
    return this;
  }

  /**
   * Get listens
   * @return listens
   */
  @javax.annotation.Nonnull
  public List<PlayingNowForUserPayloadListensInner> getListens() {
    return listens;
  }

  public void setListens(List<PlayingNowForUserPayloadListensInner> listens) {
    this.listens = listens;
  }


  public PlayingNowForUserPayload playingNow(Boolean playingNow) {
    this.playingNow = playingNow;
    return this;
  }

  /**
   * Get playingNow
   * @return playingNow
   */
  @javax.annotation.Nonnull
  public Boolean getPlayingNow() {
    return playingNow;
  }

  public void setPlayingNow(Boolean playingNow) {
    this.playingNow = playingNow;
  }


  public PlayingNowForUserPayload userId(String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nonnull
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayingNowForUserPayload playingNowForUserPayload = (PlayingNowForUserPayload) o;
    return Objects.equals(this.count, playingNowForUserPayload.count) &&
        Objects.equals(this.listens, playingNowForUserPayload.listens) &&
        Objects.equals(this.playingNow, playingNowForUserPayload.playingNow) &&
        Objects.equals(this.userId, playingNowForUserPayload.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, listens, playingNow, userId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayingNowForUserPayload {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    listens: ").append(toIndentedString(listens)).append("\n");
    sb.append("    playingNow: ").append(toIndentedString(playingNow)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("count");
    openapiFields.add("listens");
    openapiFields.add("playing_now");
    openapiFields.add("user_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("count");
    openapiRequiredFields.add("listens");
    openapiRequiredFields.add("playing_now");
    openapiRequiredFields.add("user_id");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PlayingNowForUserPayload
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PlayingNowForUserPayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PlayingNowForUserPayload is not found in the empty JSON string", PlayingNowForUserPayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PlayingNowForUserPayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PlayingNowForUserPayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PlayingNowForUserPayload.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("listens").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `listens` to be an array in the JSON string but got `%s`", jsonObj.get("listens").toString()));
      }

      JsonArray jsonArraylistens = jsonObj.getAsJsonArray("listens");
      // validate the required field `listens` (array)
      for (int i = 0; i < jsonArraylistens.size(); i++) {
        PlayingNowForUserPayloadListensInner.validateJsonElement(jsonArraylistens.get(i));
      };
      if (!jsonObj.get("user_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `user_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PlayingNowForUserPayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PlayingNowForUserPayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PlayingNowForUserPayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PlayingNowForUserPayload.class));

       return (TypeAdapter<T>) new TypeAdapter<PlayingNowForUserPayload>() {
           @Override
           public void write(JsonWriter out, PlayingNowForUserPayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PlayingNowForUserPayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PlayingNowForUserPayload given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PlayingNowForUserPayload
   * @throws IOException if the JSON string is invalid with respect to PlayingNowForUserPayload
   */
  public static PlayingNowForUserPayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PlayingNowForUserPayload.class);
  }

  /**
   * Convert an instance of PlayingNowForUserPayload to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

